name: SnapWeaver

prompt:
  product_name: SnapWeaver
  use_translator: false
  synonyms:
    sh: snapshot
  idk_phrases:
    ru: Ответа нет!

tenants:
  snapweaver:
    name: SnapWeaver
    
    widget_settings:
      examples: 
        - How to install SnapWeaver?
      filters:
        - property: doc
          type: eq
          widget: single
          title: Document Type
          choices: 
            - DOC
            - FAQ
            - TCK

    crawlers:
      docs:
        module: web
        parameters:
          metadata:
            document_type: DOC
          start_urls:
            - https://snapweaver.staging.serenitygpt.com/index.html
          match_urls:
            - https://snapweaver.staging.serenitygpt.com/(?!faq\.html$).*
          text_selectors:
            - div[class="container"]

      faq:
        module: web
        parameters:
          metadata:
            document_type: FAQ
          start_urls:
            - https://snapweaver.staging.serenitygpt.com/faq.html
          text_selectors:
            - main

      tickets:
        module: snapweaver.src.tickets_crawler.run
        parameters:
          source: .
          public_url: http://jira.local
          metadata:
            document_type: "TCK"