questions:
  snapweaver:
    - question: What is SnapWeaver?
      target_url: https://snapweaver.staging.serenitygpt.com/introduction.html
    - question: How to install SnapWeaver?
      target_url: https://snapweaver.staging.serenitygpt.com/installation.html
  csv:
    - question: Give me examples of tickets with login isuues
      instructions: should mention ticket "Login issue"

